spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park?useUnicode=true&characterEncoding=utf-8
    username: root
    password: loveyiran

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    level:
      root: warn
      com.henryzhang: info
    file: log/blog-pro.log
server:
  port: 8081